# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs all the tests"
  lane :tests do
    run_tests(scheme: "SudokuKillerApp")
  end

  desc "Take screenshots"
  lane :screenshots do
    capture_screenshots
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: "SF87XC2GQA",
      issuer_id: "a43e1ea3-3ccd-4012-96d8-a1d3504f23c1",
      key_filepath: "./fastlane/AuthKey_SF87XC2GQA.p8",
      in_house: false
    )
    increment_version_number(
      bump_type: "patch" # hoặc "minor", "major"
    )
    increment_build_number(xcodeproj: "SudokuKillerApp.xcodeproj")
    build_app(workspace: "SudokuKillerApp.xcworkspace", scheme: "SudokuKillerApp")
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
