name: Build and Distribute on Push to Master

on:
  push:
    branches:
      - master

jobs:
  build-ios:
    name: Build and Upload iOS to TestFlight
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Disable Synchronized Groups (fix Xcode 15.4 crash)
        run: |
          defaults write com.apple.dt.Xcode IDEFileSystemSynchronizedGroups -bool false
          defaults write com.apple.dt.Xcode IDEEnableFileSystemSynchronizedGroups -bool NO
          defaults write com.apple.dt.Xcode IDEFileSystemSynchronizedGroupsEnabled -bool false

      - name: Resolve Swift Packages
        run: |
          xcodebuild -resolvePackageDependencies \
            -workspace SudokuKillerApp.xcworkspace \
            -scheme SudokuKillerApp

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          yarn install
          npx pod-install

      - name: Restore AuthKey from base64
        run: |
          echo "$APP_STORE_CONNECT_API_KEY_BASE64" | base64 -d > ios/fastlane/AuthKey.p8
        env:
          APP_STORE_CONNECT_API_KEY_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}

      - name: Install fastlane (global)
        run: |
          sudo gem install fastlane
          fastlane --version

      - name: Run Fastlane beta_github (iOS)
        run: |
          cd ios
          fastlane beta_github
